### ISSUE TITLE
Create UI tests for app and job recommendations

### ISSUE THREAD

**Issue by ezhang17** [nguyenha1910/opentowork#109]
Goal is to get this done by Sunday 3/10

@nguyenha1910 - app tests
@kellyzwang @ezhang17 - job recommendations

**Comment by nguyenha1910** [comment]
- [x] Test expander: title, company name, link
- [x] Test click on apply, a row will add to the expander
- [x] Test job_list: title, company name, link
- [x] Test update job posting
