### ISSUE TITLE
Spacy Requirements in Environment

### ISSUE THREAD

**Issue by ezhang17** [nguyenha1910/opentowork#34]
Tried running python -m streamlit run pages/home.py in opentowork environment created from environment.yml, gave an error about needing en_core_web_lg.
Is there a way to get this in the environment setup?
(Had to run python -m spacy download en_core_web_lg)

**Comment by nguyenha1910** [comment]
Have you tried this? [Link](https://spacy.io/usage/models#production)

**Comment by ezhang17** [comment]
Followed the instructions and added it to the requirements.txt file, it should work now !!
