### ISSUE TITLE
Error in showing percentage (StreamlitAPIException: Progress Value has invalid value [0.0, 1.0]: 1.000000)

### ISSUE THREAD

**Issue by kellyzwang** [nguyenha1910/opentowork#63]
got a score 1.0000001192092896

**Comment by ezhang17** [comment]
![image](https://github.com/nguyenha1910/opentowork/assets/155691933/e48af305-20dc-40da-b7c5-87028c6daf10)
(gave around 80% the first time and over 100% the second.................)
(edit: found that removing the brackets around job_posting_skills in line 22 of sim_score_calculator_new.py gives this error, but keeping the brackets gives another error about list index out of range for jobs that only have 1 skill)

**Comment by kellyzwang** [comment]
calculating score using whole jd content and whole resume content fixed this bug, now using the 2 skill lists to show "x out of y skills presented in your resume."
