### ISSUE TITLE
Add no jobs found message to frontend

### ISSUE THREAD

**Issue by ezhang17** [nguyenha1910/opentowork#75]
In the case that the job scraper returns no jobs after clicking the "update jobs" button, output a message to the user "Oops, no jobs were found. Please try again." instead of having a blank screen.

**Comment by kellyzwang** [comment]
https://github.com/nguyenha1910/opentowork/pull/133 shows the message if 1) there's no csv found in the csvs folder, 2) the csv only has header, 3) the rows are all NULL values (except header)
